[project]
name = "homepage"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "sphinx>=2.4",
    "sphinx-reredirects>=0.1.6",
    "tinkerer",
]

[tool.uv.sources]
tinkerer = { git = "https://github.com/bnmnetp/tinkerer.git" }
